# -*- coding: utf-8 -*-
"""week05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvrHjxr4xqiYW7IucuabJuBxWxqyuQew
"""

# Step 1: Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Additional imports for scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Step 2: Load the digits dataset
digits = load_digits()
X = digits.data     # flattened 8x8 pixel images (64 features)
y = digits.target   # digit labels (0–9)

# Step 3: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 4: Normalize/Scale the data
# Uncomment one of the scalers below
# No scaling (original data) ---
X_train_scaled = X_train
X_test_scaled = X_test

# Standard Scaler (mean=0, std=1) ---
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Min-Max Scaler (scaled to [0, 1]) ---
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 5: Create and train the Perceptron model
model = Perceptron(max_iter=3000, eta0=0.001, random_state=42)
model.fit(X_train_scaled, y_train)

# Step 6: Make predictions
y_pred = model.predict(X_test_scaled)

# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Step 8: Plot confusion matrix
import seaborn as sns
import pandas as pd

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(pd.DataFrame(cm), annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.show()
